import { expect, test } from '@playwright/test';

import { authFile } from './support/authState';

/**
 * The Phase 05 surfaces, through a real browser against a real backend.
 *
 * These cover what only an end-to-end test can: that the audit trail actually
 * records what the browser just did, that the export leaves the server with the
 * right columns in it, and that the last-Owner guard reaches the screen as a
 * sentence the user can act on rather than a generic failure.
 */

test.describe('the activity log, as an owner', () => {
  test.use({ storageState: authFile('owner') });

  test('shows real entries with an actor and an action', async ({ page }) => {
    await page.goto('/activity');

    await expect(page.getByRole('heading', { name: 'Activity log' })).toBeVisible();

    // The seeded history is written with auditing paused — a fabricated past
    // must not claim to be a record of user actions — so the entries here are
    // the ones this suite has generated by signing in.
    const table = page.getByRole('table');
    await expect(table).toBeVisible();

    // Scoped to the table: the action filter above it holds an
    // <option>auth.login</option> that an unscoped text match finds first, and
    // an <option> is never "visible".
    await expect(table.getByText('login').first()).toBeVisible();
  });

  test('records the sign-ins this suite performed', async ({ page }) => {
    await page.goto('/activity?action=auth.login');

    await expect(page.getByRole('row').nth(1)).toBeVisible();
  });

  test('pages by cursor, offering no page numbers', async ({ page }) => {
    await page.goto('/activity');

    /*
     * The absence is the assertion. Offset paging over the highest-growth
     * table gets slower as it fills, and shifts entries between pages while a
     * reader is working through them — an audit tool that can skip an entry
     * is not an audit tool.
     */
    await expect(page.getByRole('button', { name: 'Older' })).toBeVisible();
    await expect(page.getByText(/page \d+ of \d+/i)).toHaveCount(0);
  });

  test('states that it cannot be edited', async ({ page }) => {
    await page.goto('/activity');

    await expect(page.getByText(/append-only/i)).toBeVisible();
  });
});

test.describe('the activity log, as staff', () => {
  test.use({ storageState: authFile('staff') });

  test('is not in the navigation and is refused by direct URL', async ({ page }) => {
    await page.goto('/dashboard');

    const nav = page.getByRole('navigation', { name: 'Main' });
    await expect(nav.getByRole('link', { name: 'Activity log' })).toHaveCount(0);

    /*
     * Wait for the SERVER's refusal before asserting the screen. The dev API
     * (`php artisan serve`) handles one request at a time, so in a full run
     * this request can queue behind an export or a dashboard for longer than
     * the assertion timeout — the test was measuring the queue, not the page.
     */
    const refused = page.waitForResponse(
      (response) =>
        new URL(response.url()).pathname === '/api/v1/activity' && response.status() === 403,
    );

    await page.goto('/activity');
    await refused;

    await expect(page.getByText(/not available for your role/i).first()).toBeVisible();
  });
});

/* -------------------------------------------------------------------------- */
/* Export                                                                      */
/* -------------------------------------------------------------------------- */

test.describe('export, as an owner', () => {
  test.use({ storageState: authFile('owner') });

  /*
   * ONE download for the whole describe, deliberately.
   *
   * Export is rate-limited to ten per hour per user, because bulk extraction
   * is the exfiltration vector in this system (SECURITY.md §7). A suite that
   * spends two of those ten every run can be run five times an hour before it
   * starts failing against a safeguard that is working correctly — which is
   * the same mistake the Phase 03 suite made with the login limiter, in a new
   * costume. The limit is right; downloading the same file twice to make two
   * assertions about it was the waste.
   */
  test('downloads the filtered view, named and redacted by the server', async ({ page }) => {
    await page.goto('/products?search=a');

    /*
     * Wait for real rows before clicking. The button is in the DOM from the
     * first paint, but its handler is not attached until React hydrates —
     * clicking in between does nothing at all, silently, and the test then
     * waits ten seconds for a download that was never started.
     */
    await expect(page.getByRole('row').nth(1)).toBeVisible();

    const [download] = await Promise.all([
      page.waitForEvent('download'),
      page.getByRole('button', { name: 'Export CSV' }).click(),
    ]);

    // The SERVER names the file, date stamp and all. Reading it back requires
    // Content-Disposition to be CORS-exposed, or the browser hides the header
    // from JavaScript and the client silently invents a name instead.
    expect(download.suggestedFilename()).toMatch(/^products-\d{4}-\d{2}-\d{2}\.csv$/);

    const stream = await download.createReadStream();
    const chunks = [];

    for await (const chunk of stream) chunks.push(chunk);

    const body = Buffer.concat(chunks).toString('utf8');
    const [header, ...rows] = body.trim().split('\n');

    // A cost column, because an Owner may see cost. The column set comes from
    // the same resource the screen uses, so redaction is inherited.
    expect(header).toContain('Cost');
    expect(rows.length).toBeGreaterThan(0);

    /*
     * "Export" means "export what I am looking at". The screen was filtered to
     * names containing "a", and the file has to agree — the server runs the
     * list and the export through one query definition, and this asserts the
     * UI actually hands its live filters over.
     */
    const listed = await page.getByRole('row').nth(1).innerText();
    const firstName = listed.split('\t')[1] ?? '';

    if (firstName.trim() !== '') {
      expect(body).toContain(firstName.trim());
    }
  });
});

test.describe('export, as staff', () => {
  test.use({ storageState: authFile('staff') });

  test('is not offered at all', async ({ page }) => {
    // Staff hold no export ability of any kind, so the control is absent
    // rather than present and refused.
    await page.goto('/products');

    await expect(page.getByRole('heading', { name: 'Products' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Export CSV' })).toHaveCount(0);
  });
});

/* -------------------------------------------------------------------------- */
/* Users                                                                       */
/* -------------------------------------------------------------------------- */

test.describe('users, as an owner', () => {
  test.use({ storageState: authFile('owner') });

  test('lists the seeded accounts with their roles', async ({ page }) => {
    await page.goto('/settings/users');

    await expect(page.getByRole('heading', { name: 'Users' })).toBeVisible();
    // Cells, not text: the signed-in owner's own address is also in the header.
    await expect(page.getByRole('cell', { name: 'owner@opsight.test' })).toBeVisible();
    await expect(page.getByRole('cell', { name: 'staff@opsight.test' })).toBeVisible();
  });

  test('refuses to demote the last Owner, and says what to do instead', async ({ page }) => {
    await page.goto('/settings/users');

    const row = page.getByRole('row').filter({ hasText: 'owner@opsight.test' });

    await row.getByRole('combobox').selectOption('manager');

    /*
     * The guard is an availability guarantee, not a permission: Owner is the
     * only role that can promote anyone or change settings, so an
     * installation with no active Owner cannot be recovered through the
     * application at all. The message has to say how to get past it.
     */
    await expect(page.getByText(/last active Owner/i)).toBeVisible();
    await expect(page.getByText(/Promote another user/i)).toBeVisible();
  });

  test('explains that deactivation is not deletion before confirming', async ({ page }) => {
    await page.goto('/settings/users');

    const row = page.getByRole('row').filter({ hasText: 'analyst@opsight.test' });

    await row.getByRole('button', { name: 'Deactivate' }).click();

    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.getByText(/lose access on their next request/i)).toBeVisible();
    await expect(page.getByText(/stays on record/i)).toBeVisible();

    // Left unconfirmed: this suite shares one database with the others, and
    // deactivating the analyst would break their sign-in elsewhere.
    await page.getByRole('button', { name: 'Cancel' }).click();
  });
});

test.describe('users, as a manager', () => {
  test.use({ storageState: authFile('manager') });

  test('cannot reach user administration', async ({ page }) => {
    // Manager holds full operational and financial authority and no authority
    // over access control — the one boundary a Manager does not cross.
    await page.goto('/settings/users');

    await expect(page.getByText(/not available for your role/i).first()).toBeVisible();
  });
});

/* -------------------------------------------------------------------------- */
/* Settings                                                                    */
/* -------------------------------------------------------------------------- */

test.describe('settings', () => {
  test.use({ storageState: authFile('owner') });

  test('warns that two fields move historical figures', async ({ page }) => {
    await page.goto('/settings');

    await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible();

    // Stated before the change, on the fieldset itself.
    await expect(page.getByText(/moves which month, quarter or year/i)).toBeVisible();
  });

  test('raises a specific warning once such a field is actually changed', async ({ page }) => {
    await page.goto('/settings');

    await page.getByLabel('Fiscal year starts').selectOption('7');

    await expect(
      page.getByText(/change the totals reported for periods that have already/i),
    ).toBeVisible();

    // Not saved: this database is shared with the metric assertions in the
    // other specs, and a July fiscal year would move every YTD figure.
  });
});

test.describe('settings, as staff', () => {
  test.use({ storageState: authFile('staff') });

  test('are not reachable at all', async ({ page }) => {
    /*
     * Default deny. The read was briefly open to every role on the grounds
     * that currency and timezone are formatting inputs rather than secrets —
     * but the screens that format money already receive both in the meta of
     * the analytics responses they make anyway, so nothing outside this
     * screen needed the endpoint and the exception was not paying for itself.
     */
    await page.goto('/dashboard');

    const nav = page.getByRole('navigation', { name: 'Main' });
    await expect(nav.getByRole('link', { name: 'Settings' })).toHaveCount(0);

    await page.goto('/settings');
    await expect(page.getByText(/not available for your role/i).first()).toBeVisible();
  });
});
